/**
 * GeminiService - Handles communication with Google's Gemini Flash API
 * This service allows the "Smart Dramaturg" to generate real AI content.
 */
class GeminiService {
    constructor() {
        // [IMPORTANT] REPLACE 'YOUR_API_KEY' WITH YOUR ACTUAL GEMINI API KEY
        // You can get a key from: https://aistudio.google.com/app/apikey
        this.apiKey = 'AIzaSyDonDKS6UDX94k5jZ7T36yIPunmx7tfxsk';

        this.baseUrl = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent';
    }

    /**
     * Sends a prompt to Gemini and returns the generated text.
     * @param {string} prompt - The user/system prompt to send.
     * @returns {Promise<string>} - The text response from Gemini.
     */
    async generateContent(prompt) {
        if (this.apiKey === 'YOUR_API_KEY' || !this.apiKey) {
            throw new Error('API Key is missing. Please add your Gemini API Key in js/gemini-service.js');
        }

        const url = `${this.baseUrl}?key=${this.apiKey}`;

        const payload = {
            contents: [{
                parts: [{
                    text: prompt
                }]
            }]
        };

        try {
            const response = await fetch(url, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(payload)
            });

            if (!response.ok) {
                const errorData = await response.json();
                throw new Error(`Gemini API Error: ${errorData.error?.message || response.statusText}`);
            }

            const data = await response.json();

            // Extract text from response structure
            if (data.candidates && data.candidates.length > 0 && data.candidates[0].content) {
                return data.candidates[0].content.parts[0].text;
            } else {
                throw new Error('No content generated by Gemini.');
            }

        } catch (error) {
            console.error('GeminiService Error:', error);
            throw error;
        }
    }

    /**
     * Helper to clean up Markdown code blocks from JSON responses.
     * Often LLMs wrap JSON in ```json ... ```
     */
    cleanJson(text) {
        return text.replace(/```json/g, '').replace(/```/g, '').trim();
    }
}

// Export a single instance
window.geminiAgent = new GeminiService();
